SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 15  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 20
PLAYER_SPEED = 20

SHOT_RADIUS = 3
PLAYER_SHOOT_SPEED = 100
PLAYER_SHOOT_COOLDOWN = 3